-- T?o user GIANGVIEN và ??t m?t kh?u
CREATE LOGIN GIANGVIEN WITH PASSWORD = '1';

-- T?o user GIAOVU và ??t m?t kh?u
CREATE LOGIN GIAOVU WITH PASSWORD = '1';

-- T?o user SINHVIEN và ??t m?t kh?u
CREATE LOGIN SINHVIEN WITH PASSWORD = '1';


-- Phân quy?n cho GIAOVU
CREATE USER GIAOVU FOR LOGIN GIAOVU;
EXEC sp_addrolemember 'db_datareader', 'GIAOVU';
EXEC sp_addrolemember 'db_datawriter', 'GIAOVU';
-- GIAOVU không có quy?n xóa
DENY DELETE ON DATABASE::QuanLyDeTai TO GIAOVU;

-- Phân quy?n cho GIANGVIEN
CREATE USER GIANGVIEN FOR LOGIN GIANGVIEN;

-- C?p quy?n SELECT cho các b?ng liên quan
GRANT SELECT ON GIAOVIEN TO GIANGVIEN;
GRANT SELECT ON DETAI TO GIANGVIEN;
GRANT SELECT ON SV_DETAI TO GIANGVIEN;
GRANT SELECT ON HOIDONG TO GIANGVIEN;
GRANT SELECT ON HOIDONG_GV TO GIANGVIEN;

-- C?p quy?n UPDATE trên b?ng GIAOVIEN
GRANT UPDATE ON GIAOVIEN TO GIANGVIEN;


-- Phân quy?n cho SINHVIEN
CREATE USER SINHVIEN FOR LOGIN SINHVIEN;

-- C?p quy?n SELECT cho các b?ng liên quan
GRANT SELECT ON SINHVIEN TO SINHVIEN;
GRANT SELECT ON DETAI TO SINHVIEN;
GRANT SELECT ON HOIDONG TO SINHVIEN;

-- C?m quy?n DELETE cho GIAOVU
DENY DELETE TO GIAOVU;

-- C?m quy?n DELETE cho GIANGVIEN
DENY DELETE TO GIANGVIEN;

-- C?m quy?n DELETE cho SINHVIEN
DENY DELETE TO SINHVIEN;