use quanlydetai
go


-- View 4.1
CREATE VIEW View_ThongTinDeTai AS  
SELECT DETAI.MSDT, DETAI.TENDT, GIAOVIEN.MSGV,TENGV, DIEM  
FROM GIAOVIEN JOIN GV_UVDT ON GIAOVIEN.MSGV = GV_UVDT.MSGV  
JOIN DETAI ON DETAI.MSDT = GV_UVDT.MSDT

-- View 4.2
SELECT  
    HD.MSHD AS 'Mã số hội đồng',  
    DT.TENDT AS 'Tên đề tài',  
    HD.PHONG AS 'Phòng',  
    CONVERT(VARCHAR, HD.NGAYHD, 103) AS 'Ngày hội đồng',  -- Format 103: dd/mm/yyyy  
    GV.TENGV AS 'Chủ tịch hội đồng',  
    AVG(ISNULL(GV_HDDT.DIEM, 0) + ISNULL(GV_PBDT.DIEM, 0) + ISNULL(GV_UVDT.DIEM, 0)) AS 'Điểm trung bình'  
FROM  
    HOIDONG HD  
JOIN  
    HOIDONG_DT ON HD.MSHD = HOIDONG_DT.MSHD  
JOIN  
    DETAI DT ON HOIDONG_DT.MSDT = DT.MSDT  
JOIN  
    GIAOVIEN GV ON HD.MSGV = GV.MSGV  
LEFT JOIN  
    GV_HDDT ON HOIDONG_DT.MSDT = GV_HDDT.MSDT AND GV.MSGV = GV_HDDT.MSGV  
LEFT JOIN  
    GV_PBDT ON HOIDONG_DT.MSDT = GV_PBDT.MSDT AND GV.MSGV = GV_PBDT.MSGV  
LEFT JOIN  
    GV_UVDT ON HOIDONG_DT.MSDT = GV_UVDT.MSDT AND GV.MSGV = GV_UVDT.MSGV  
GROUP BY  
    HD.MSHD, DT.TENDT, HD.PHONG, HD.NGAYHD, GV.TENGV, HD.NGAYHD; 